name: 'gtm_pipeline'
version: '1.0.0'

profile: 'gtm_pipeline'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  gtm_pipeline:
    staging:
      +schema: staging
      +materialized: view
    mart:
      +schema: mart
      +materialized: table
